### ISSUE TITLE
Project could use a CONTRIBUTING.md

### ISSUE THREAD

**Issue by slifty** [servinglynk/hmis-lynk-open-source#8]
It would be great to have a CONTRIBUTING.md (see [this](https://github.com/OpenTechStrategies/psm/blob/master/CONTRIBUTING.md) for a reasonable example).  This would help potential contributors like myself make sure to follow the project's guidelines.

**Comment by eric-jahn** [comment]
Dan, this is a great idea.  We have all our issues and docs/wikis in the other repo (same name, but ends in -docs).  Could you move this over to that repo?  We can start with yours and check one in then.  Thanks!

**Comment by slifty** [comment]
Absolutely!
